/**
 * The screen-selection layer for the three places a sign-in or
 * confirmation flow turns UNTRUSTED input into a rendered notice (see
 * docs/multi-user-login-acceptance-criteria.md B2, B5, B5b, and the header
 * of this module's test file for the full reasoning). Pure and edge-safe,
 * like `./access.ts`: this module imports NOTHING, so it can be called from
 * a Server Component, a route handler, or a client component without
 * dragging in anything with side effects.
 *
 * Every function here returns a TOKEN out of a closed set, never a message.
 * A function that returned a string built from its input would let a caller
 * interpolate an untrusted value into the page - exactly the failure this
 * module exists to design out. The caller (the screen itself) owns the copy
 * for each token; this module only owns which token, if any, applies.
 */

/**
 * The complete, closed set of notices a login-area screen can render.
 *
 * Three of these - `check-email`, `link-missing` and `wrong-account` - are
 * set directly by a flow that already knows they are true (the sign-up
 * screen after it sends a confirmation email; the confirmation route before
 * it ever calls the provider, when there is no token to call it with; and an
 * OAuth callback that resolves to a second address), never derived from an
 * untrusted string. No function in this module produces them - see the doc
 * comments on `noticeFromStateParam` and `noticeFromConfirmError` below, and
 * this module's test file, which pins that a crafted URL can never reach a
 * "we emailed you" or "wrong account" screen that is not true.
 */
export const AUTH_NOTICES = [
  "check-email",
  "link-invalid",
  "link-missing",
  "pending",
  "suspended",
  "unavailable",
  "wrong-account",
] as const;

/** A member of the closed notice set above. */
export type AuthNotice = (typeof AUTH_NOTICES)[number];

/**
 * Selects a notice from the sign-in gate's `?state=` query parameter.
 *
 * `state` is attacker-authored: anyone can send a colleague
 * `/login?state=suspended` and they read an alarming message on the real
 * domain with a real certificate. So this function accepts only the three
 * values the gate's own redirect (`loginRedirectFor` in `./access.ts`) can
 * actually produce, and returns `null` for everything else, including:
 *
 * - `"active"` and `"owner"` - `loginRedirectFor` returns `null` for both of
 *   these decisions (the request is allowed to proceed, no redirect
 *   happens), so a `/login` request carrying either one was hand-crafted,
 *   not generated by the gate. The honest response is the plain sign-in
 *   card, not a notice that claims to explain a redirect that never
 *   happened.
 * - `"anonymous"` - a real, gate-producible decision, but "you are not
 *   signed in" is noise on a page whose entire purpose is to sign in.
 * - any other string, and any non-string shape a query parameter can arrive
 *   as (`?state=a&state=b` reaches a page component as `string[]`, and a
 *   malformed request can hand this function almost anything).
 *
 * Written as an explicit switch over the three accepted literals rather than
 * a membership check that echoes back whatever it was given: the two are
 * equally safe here, but the switch keeps the accepted set visible at the
 * call site, and is what forces a decision if `AccessDecision` ever grows a
 * fourth redirectable state without this function being taught about it.
 */
export function noticeFromStateParam(raw: unknown): AuthNotice | null {
  if (typeof raw !== "string") {
    return null;
  }

  switch (raw) {
    case "pending":
    case "suspended":
    case "unavailable":
      return raw;
    default:
      return null;
  }
}

/**
 * The result of classifying a sign-in failure. A union of one value today,
 * on purpose: see `mapSignInFailure`'s own doc comment for why every code it
 * recognises, and every code it does not, produces the same outcome.
 */
export type SignInFailureNotice = "generic";

/**
 * Classifies a sign-in failure code from the auth provider into a single
 * generic outcome, never a distinguishable one.
 *
 * The provider's own codes distinguish "wrong password" from "unconfirmed"
 * from "banned", and rendering that distinction on a sign-in screen
 * enumerates accounts:
 *
 * - `invalid_credentials` alone discloses nothing - it covers both a wrong
 *   password and no account at all for that address.
 * - `email_not_confirmed` proves the address HAS an account.
 * - `user_banned` proves it has one AND that it is currently suspended -
 *   suspension now bans the account at the auth provider (see
 *   `./access.ts`'s `AccessStatus`), so this is the ordinary shape of "this
 *   account is suspended", not an edge case.
 *
 * All three collapse to `"generic"`, and so does anything this function
 * does not recognise: a provider that adds a new failure code later must
 * not be able to silently start leaking account state through this
 * function before it is deliberately taught the new code. The switch below
 * enumerates the codes this module has actually observed so that fact is
 * visible at the call site, even though every branch - including the
 * default - returns the same token.
 *
 * NOT handled here: `signup_disabled`. That code is a property of the
 * DEPLOYMENT (sign-ups are turned off entirely), not of any one account, so
 * the enumeration argument above does not apply to it - collapsing it into
 * `"generic"` would just be a worse message, not a safer one. It gets its
 * own notice on the screen side once that flow is built; do not fold it
 * into this function's default case.
 */
export function mapSignInFailure(code: unknown): SignInFailureNotice {
  switch (typeof code === "string" ? code : "") {
    case "invalid_credentials":
    case "email_not_confirmed":
    case "user_banned":
    default:
      return "generic";
  }
}

/**
 * Maps a confirmation-link failure code to a notice. Always
 * `"link-invalid"`: the provider returns the same code (`otp_expired`) for
 * an expired link and an already-used one, so a screen that distinguished
 * them would be describing a difference that does not exist at the source
 * of truth. Every other verification failure code collapses into the same
 * notice, for the same reason `mapSignInFailure` collapses its codes - a
 * code this function does not recognise must not produce a screen more
 * specific than one it does. The switch below enumerates the codes this
 * module has actually observed so that fact is visible at the call site,
 * even though every branch - including the default - returns the same
 * token.
 *
 * A literal `"missing"` is deliberately NOT special-cased into
 * `"link-missing"` here. The two are not the same situation: a request with
 * no token at all never reaches the auth provider, so it never produces a
 * failure code for this function to map in the first place. That case is
 * detected, and `"link-missing"` is set directly, by the confirmation route
 * itself before it ever calls the provider - see `AUTH_NOTICES`'s own doc
 * comment. Passing `"missing"` through this function anyway exists only to
 * pin that this mapper cannot be talked into producing `"link-missing"` by
 * feeding it a suggestively-named string.
 */
export function noticeFromConfirmError(code: unknown): AuthNotice {
  switch (typeof code === "string" ? code : "") {
    case "otp_expired":
    case "otp_disabled":
    case "validation_failed":
    case "bad_jwt":
    case "unexpected_failure":
    default:
      return "link-invalid";
  }
}
