// The internal "this cartridge was built by Course Build" stamp - a marker
// written INSIDE a cartridge zip (not just recorded as a database field
// alongside it), so the marker survives a download-then-re-upload round
// trip. Without this, the only record that a cartridge was app output lived
// in the `generated` flag on the course's `export_files` row
// (courses-table-helpers.ts's `isGeneratedExportFile`); that flag is EXTERNAL
// metadata and is gone the moment the instructor downloads the file and
// hands it back to the app as a fresh upload - which is how the app ended up
// building a course from material it had itself invented (docs/REGRESSION.md
// entry 202 AC5, which left this exact residual).
//
// This module is intentionally pure (no zip I/O, no JSZip import) so it can
// be imported from BOTH sides of the round trip without pulling either one's
// concerns into the other: the writer (src/lib/workflows/common-cartridge.ts)
// calls buildCartridgeStampJson to produce the file content; the reader
// (src/lib/cartridge-import.ts) calls readCartridgeStamp to validate content
// it already pulled out of a zip entry. Neither side needs to agree on
// anything beyond the exported constants and this shape.
//
// Placement: a dedicated file at a fixed, app-specific zip path
// (CARTRIDGE_STAMP_PATH) - reusing the "ta-cartridge" token this app already
// stamps onto every manifest it writes (buildManifestXml's
// `identifier="ta-cartridge"` in common-cartridge.ts) rather than inventing
// unrelated vocabulary. A dedicated unreferenced file was chosen over
// editing imsmanifest.xml's own content (the other option the backlog item
// allowed): nothing in the manifest's <resources> block points at this path,
// so Canvas/Blackboard's importers - which only act on what the manifest
// declares - simply carry it through as an inert extra file, with zero risk
// of altering how a real LMS imports this app's own cartridges. It is not a
// dotfile, so a naive re-zip (e.g. dragging files into a fresh archive,
// Mac Archive Utility) that drops hidden/OS marker files - the same failure
// mode noted in cartridge-import.ts's Blackboard-detection comment - does not
// drop this one. Verified against a real Canvas export (26SS_INFO_1020_2A,
// 12 modules, ~61MB, downloaded from a live course): no file at this path,
// no file anywhere in the archive matching /ta-cartridge|teaching|stamp/i,
// and its own manifest `identifier` is an opaque Canvas-generated hash - so a
// genuine instructor export cannot coincidentally satisfy this stamp.
export const CARTRIDGE_STAMP_PATH = "ta-cartridge-generated.json";

// Stable machine-readable app identifier. Distinct from the prose string
// already written into course_settings/canvas_export.txt for the "canvas"
// flavor ("Generated by the teaching assistant app.", common-cartridge.ts) -
// that file is Canvas's own reserved settings file (a real Canvas export
// carries one too, with unpredictable content - Canvas's own sample export
// used for reuse-survey verification had unrelated joke text there), so it is
// never safe to pattern-match for detection. This constant is this module's
// one new, dedicated vocabulary for the concept, deliberately not a second
// parallel one: the display string a person actually sees ("Generated by
// Course Build" - FilesCell.tsx's label for the EXTERNAL `generated` DB flag)
// rides along unchanged in `generatedBy` below.
export const CARTRIDGE_STAMP_APP_ID = "teaching-assistant";
const CARTRIDGE_STAMP_GENERATED_BY = "Course Build";
const CARTRIDGE_STAMP_KIND = "course-cartridge";
const CARTRIDGE_STAMP_VERSION = 1;

/** The parsed, validated shape of a stamp this app wrote. */
export interface CartridgeStamp {
  app: string;
  generatedBy: string;
  kind: string;
  stampVersion: number;
  /** UTC ISO-8601 timestamp of when buildCartridgeStampJson produced this file. */
  generatedAt: string;
  /**
   * The course or week title passed to the cartridge builder at the time -
   * whatever this app already had in hand (buildCommonCartridge's
   * courseTitle, buildWeekCartridge's weekTitle), never anything
   * user-identifying (no instructor name, no email, no account id). Null
   * when the builder was not given a usable title.
   */
  title: string | null;
}

/**
 * Build the stamp file's JSON content. Called by the cartridge writer
 * (common-cartridge.ts) for every cartridge it produces, unconditionally -
 * mirroring saveCourseExportFile's own unconditional `generated: true`
 * (registry-helpers.ts), because both exist solely to mark app output, with
 * no caller opt-in to omit it.
 */
export function buildCartridgeStampJson(opts: { title?: string | null }): string {
  const stamp: CartridgeStamp = {
    app: CARTRIDGE_STAMP_APP_ID,
    generatedBy: CARTRIDGE_STAMP_GENERATED_BY,
    kind: CARTRIDGE_STAMP_KIND,
    stampVersion: CARTRIDGE_STAMP_VERSION,
    generatedAt: new Date().toISOString(),
    title: opts.title && opts.title.trim() ? opts.title.trim() : null,
  };
  return JSON.stringify(stamp);
}

/**
 * Validate and parse a stamp file's raw content. Returns null for EVERY
 * negative case - absent file (`raw` null/undefined), empty content,
 * malformed JSON, a JSON value that is not a plain object, or an object
 * missing/mismatching the required `app`/`kind` fields - rather than
 * throwing. This is the degrade-safely half of the contract: an unstamped or
 * corrupted cartridge must read exactly like a plain instructor export, not
 * raise an error that a caller would need to remember to catch. Only a
 * POSITIVE match (this exact app id and kind) changes any caller's behavior.
 *
 * `stampVersion` is read but not gated on - a future format bump only needs
 * to add fields here, not reject stamps this version of the code cannot
 * fully interpret yet.
 */
export function readCartridgeStamp(raw: string | null | undefined): CartridgeStamp | null {
  if (!raw || !raw.trim()) return null;
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return null;
  }
  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) return null;
  const obj = parsed as Record<string, unknown>;
  if (obj.app !== CARTRIDGE_STAMP_APP_ID) return null;
  if (obj.kind !== CARTRIDGE_STAMP_KIND) return null;
  return {
    app: CARTRIDGE_STAMP_APP_ID,
    generatedBy: typeof obj.generatedBy === "string" ? obj.generatedBy : CARTRIDGE_STAMP_GENERATED_BY,
    kind: CARTRIDGE_STAMP_KIND,
    stampVersion: typeof obj.stampVersion === "number" ? obj.stampVersion : CARTRIDGE_STAMP_VERSION,
    generatedAt: typeof obj.generatedAt === "string" ? obj.generatedAt : "",
    title: typeof obj.title === "string" && obj.title.trim() ? obj.title : null,
  };
}
