// P3-AC4 (graphics-gap-reporting hand-off): a deck-LEVEL audit of a FINISHED
// .pptx buffer.
//
// enforceGraphicsForApplied (src/lib/slide-graphics.ts) only ever sees the
// in-memory SlideData the generator built - it can name a gap in that data,
// but it can never prove what actually landed in the .pptx file that ships.
// That in-memory-only reach is exactly what let the original measurement
// error happen (see registry.graphics-gap-reporting.test.ts's background
// comment for the full root-cause writeup): an audit that unzipped a real
// generated .pptx and counted <p:sp> shapes per slide read a "table" graphic
// as empty, because pptxgenjs renders a table via addTable as a
// <p:graphicFrame>/<a:tbl> - never a <p:sp> - so a table slide's shape count
// was indistinguishable from a slide with no graphic at all.
//
// This helper exists so that specific blind spot can never recur unnoticed:
// it counts BOTH text-bearing shapes (<p:txBody>, which every one of the
// three closed graphic kinds' own text elements uses - see
// renderSlideGraphic in src/lib/pptx.ts) AND <a:tbl> tables, so a table
// graphic is exactly as visible to this audit as a matrix2x2 or process one.
//
// Text-shape count, not raw <p:sp> count, is what makes the threshold below
// theme-independent: buildSlidesPptx's "standard" (untutored) rendering path
// draws three purely DECORATIVE <p:sp> shapes per content slide (header bar,
// accent strip, left-edge stripe) that carry no <p:txBody> at all, while its
// "themed" path draws none - so a raw shape count's own baseline differs by
// theme. A graphic's own background rects (the matrix's quadrant fills, the
// process's step boxes) are ALSO <p:sp> shapes with no <p:txBody> - only
// each graphic's TEXT (labels, items, captions, step text) adds a
// <p:txBody>. Every content slide's title contributes exactly one
// <p:txBody>, and its bullets (when any) contribute exactly one more - so
// a plain content slide never carries more than two. Any slide with MORE
// than two text shapes rendered a shape-based graphic on top of its
// title/bullets; a table graphic contributes zero extra <p:txBody> (its
// cells use <a:txBody>, a different tag, inside <a:tbl>) but is caught by
// the table count instead. See pptx-graphics-audit.test.ts for the measured
// counts this threshold is pinned against, generated by the real
// buildSlidesPptx.
//
// Diagnostic only - this module is never imported by the generation path
// (buildSlidesPptx, the workflow steps, or any server action). It exists to
// be run against a real generated deck, by a human or a test, to
// independently verify what enforceGraphicsForApplied's in-memory check
// already believes - not to gate anything itself.
//
// "Pure" here means deterministic and side-effect-free with respect to its
// input, matching how slide-graphics.ts uses the word: no network, no Date,
// no randomness. Unzipping the buffer's OWN bytes (JSZip.loadAsync) is no
// more an impurity than JSON.parse is - the same buffer always yields the
// same result.

import JSZip from "jszip";
import { GRAPHIC_REQUIRED_PREFIXES } from "./slide-graphics";

export interface PptxSlideGraphicAudit {
  /** 0-based position among CONTENT slides only - the title slide (always
   * slide1.xml, added first by buildSlidesPptx in both rendering paths) is
   * excluded, so this matches the same indexing SlideData[]/
   * enforceGraphicsForApplied already use. */
  index: number;
  /** The slide's own title, read from the first <a:t> run in its XML - the
   * title's addText call is always emitted before any other slide content
   * in both of buildSlidesPptx's rendering paths. */
  title: string;
  /** True when this slide's title starts with one of
   * GRAPHIC_REQUIRED_PREFIXES (Artifact:/Judgment Call:/Agenda:) - the SAME
   * vocabulary enforceGraphicsForApplied enforces in memory. */
  requiresGraphic: boolean;
  /** True when the slide's own XML carries a table (tableCount > 0) or more
   * than two text-bearing shapes (textShapeCount > 2) - see this module's
   * header comment for why that threshold is theme-independent. */
  hasGraphic: boolean;
  /** Count of <a:tbl> elements in the slide's XML. */
  tableCount: number;
  /** Count of <p:txBody> elements in the slide's XML (title + bullets +,
   * for a shape-based graphic, its own label/caption/item text runs). Table
   * cell text uses <a:txBody>, a different tag, so a table's own cells never
   * inflate this count - see this module's header comment. */
  textShapeCount: number;
}

// A plain content slide (no graphic) never carries more than two text
// shapes: the title (always) and the bullets (when the slide has any) - see
// this module's header comment for the full reasoning.
const BASELINE_TEXT_SHAPE_COUNT = 2;

function countOccurrences(xml: string, needle: string): number {
  let count = 0;
  let at = xml.indexOf(needle);
  while (at !== -1) {
    count++;
    at = xml.indexOf(needle, at + needle.length);
  }
  return count;
}

// XML-unescape the handful of entities pptxgenjs actually emits for text
// content (it does not emit numeric character references for these), so a
// slide title with an ampersand or a quote reads back the way it was
// written rather than escaped.
function unescapeXmlText(text: string): string {
  return text
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&amp;/g, "&");
}

function extractSlideTitle(xml: string): string {
  const match = xml.match(/<a:t>([\s\S]*?)<\/a:t>/);
  return match ? unescapeXmlText(match[1]) : "";
}

/**
 * Audit a finished .pptx buffer (as produced by buildSlidesPptx) for which
 * content slides carry a graphic, counting both text-bearing shapes and
 * <a:tbl> tables - see this module's header comment for the full reasoning
 * and why this is the one audit design that cannot repeat the <p:sp>-only
 * blind spot that originally hid a table graphic from view.
 */
export async function auditPptxGraphics(pptxBuffer: ArrayBuffer): Promise<PptxSlideGraphicAudit[]> {
  const zip = await JSZip.loadAsync(pptxBuffer);

  const slideFiles = Object.keys(zip.files)
    .map((name) => {
      const match = name.match(/^ppt\/slides\/slide(\d+)\.xml$/);
      return match ? { name, number: parseInt(match[1], 10) } : null;
    })
    .filter((f): f is { name: string; number: number } => f !== null)
    .sort((a, b) => a.number - b.number);

  // The title slide is always added first (slide1.xml) in both of
  // buildSlidesPptx's rendering paths - excluded here so `index` lines up
  // with the SlideData[] content-slide array every caller already has.
  const contentSlideFiles = slideFiles.slice(1);

  const audits: PptxSlideGraphicAudit[] = [];
  for (let i = 0; i < contentSlideFiles.length; i++) {
    const xml = await zip.files[contentSlideFiles[i].name].async("string");
    const title = extractSlideTitle(xml);
    const tableCount = countOccurrences(xml, "<a:tbl>");
    const textShapeCount = countOccurrences(xml, "<p:txBody>");
    audits.push({
      index: i,
      title,
      requiresGraphic: GRAPHIC_REQUIRED_PREFIXES.some((prefix) => title.startsWith(prefix)),
      hasGraphic: tableCount > 0 || textShapeCount > BASELINE_TEXT_SHAPE_COUNT,
      tableCount,
      textShapeCount,
    });
  }

  return audits;
}

/**
 * The subset of a deck-level audit that names a real defect: a
 * required-prefix slide (Artifact:/Judgment Call:/Agenda:) the audit found
 * with no graphic in the finished file. Mirrors enforceGraphicsForApplied's
 * own "missing" list, but computed from the FINISHED .pptx rather than the
 * in-memory slides that fed it.
 */
export function pptxSlidesMissingRequiredGraphic(
  audits: PptxSlideGraphicAudit[]
): PptxSlideGraphicAudit[] {
  return audits.filter((a) => a.requiresGraphic && !a.hasGraphic);
}
