/**
 * Hand-authored practice problems for the research library. Each entry carries
 * three parts, mirroring the slide contract the LLM generator follows:
 *
 * - exampleCode: a short, correct, worked snippet that demonstrates the concept
 *   WITHOUT solving the challenge (safe to show students before they attempt it)
 * - prompt: the challenge statement students attempt on their own
 * - solutionCode: a verified, runnable solution to that exact prompt
 *
 * Every snippet here was written and checked by hand — the deterministic engine
 * serves them verbatim rather than composing code at request time.
 */

export interface PracticeProblemEntry {
  kind: "practice_problem";
  id: string;
  title: string;
  /** Topic tags used for retrieval matching. */
  topics: string[];
  language: string;
  difficulty: "intro" | "core";
  prompt: string;
  exampleCode: string;
  solutionCode: string;
}

export const PRACTICE_PROBLEMS: PracticeProblemEntry[] = [
  {
    kind: "practice_problem",
    id: "loops-sum-even",
    title: "Sum the Even Numbers",
    topics: ["loops", "iteration", "for loop", "while loop", "range"],
    language: "python",
    difficulty: "intro",
    prompt: "Write a function sum_even(n) that returns the sum of all even numbers from 1 to n, inclusive. For example, sum_even(6) should return 12 (2 + 4 + 6).",
    exampleCode: [
      "# Worked example: summing ALL numbers from 1 to n with a loop.",
      "def total(n):",
      "    result = 0",
      "    for value in range(1, n + 1):",
      "        result = result + value",
      "    return result",
      "",
      "print(total(4))  # 10",
    ].join("\n"),
    solutionCode: [
      "def sum_even(n):",
      "    result = 0",
      "    for value in range(2, n + 1, 2):",
      "        result = result + value",
      "    return result",
      "",
      "print(sum_even(6))  # 12",
    ].join("\n"),
  },
  {
    kind: "practice_problem",
    id: "strings-count-vowels",
    title: "Count the Vowels",
    topics: ["strings", "loops", "characters", "iteration"],
    language: "python",
    difficulty: "intro",
    prompt: 'Write a function count_vowels(text) that returns how many vowels (a, e, i, o, u, in either case) appear in text. count_vowels("Hello") should return 2.',
    exampleCode: [
      "# Worked example: counting spaces in a string, character by character.",
      "def count_spaces(text):",
      "    count = 0",
      "    for ch in text:",
      '        if ch == " ":',
      "            count = count + 1",
      "    return count",
      "",
      'print(count_spaces("a b c"))  # 2',
    ].join("\n"),
    solutionCode: [
      "def count_vowels(text):",
      "    count = 0",
      "    for ch in text.lower():",
      '        if ch in "aeiou":',
      "            count = count + 1",
      "    return count",
      "",
      'print(count_vowels("Hello"))  # 2',
    ].join("\n"),
  },
  {
    kind: "practice_problem",
    id: "conditionals-letter-grade",
    title: "Assign a Letter Grade",
    topics: ["conditionals", "if statements", "branching", "comparison"],
    language: "python",
    difficulty: "intro",
    prompt: "Write a function letter_grade(score) that returns \"A\" for 90 and above, \"B\" for 80-89, \"C\" for 70-79, \"D\" for 60-69, and \"F\" below 60.",
    exampleCode: [
      "# Worked example: branching on a temperature reading.",
      "def describe_temp(fahrenheit):",
      "    if fahrenheit >= 85:",
      '        return "hot"',
      "    elif fahrenheit >= 60:",
      '        return "mild"',
      "    else:",
      '        return "cold"',
      "",
      "print(describe_temp(72))  # mild",
    ].join("\n"),
    solutionCode: [
      "def letter_grade(score):",
      "    if score >= 90:",
      '        return "A"',
      "    elif score >= 80:",
      '        return "B"',
      "    elif score >= 70:",
      '        return "C"',
      "    elif score >= 60:",
      '        return "D"',
      "    else:",
      '        return "F"',
      "",
      "print(letter_grade(85))  # B",
    ].join("\n"),
  },
  {
    kind: "practice_problem",
    id: "functions-temperature",
    title: "Convert Celsius to Fahrenheit",
    topics: ["functions", "parameters", "return values", "arithmetic"],
    language: "python",
    difficulty: "intro",
    prompt: "Write a function celsius_to_fahrenheit(c) that converts a Celsius temperature to Fahrenheit using F = C * 9/5 + 32. celsius_to_fahrenheit(100) should return 212.0.",
    exampleCode: [
      "# Worked example: a function that converts miles to kilometers.",
      "def miles_to_km(miles):",
      "    return miles * 1.60934",
      "",
      "print(miles_to_km(5))  # 8.0467",
    ].join("\n"),
    solutionCode: [
      "def celsius_to_fahrenheit(c):",
      "    return c * 9 / 5 + 32",
      "",
      "print(celsius_to_fahrenheit(100))  # 212.0",
    ].join("\n"),
  },
  {
    kind: "practice_problem",
    id: "strings-palindrome",
    title: "Check for a Palindrome",
    topics: ["strings", "slicing", "comparison"],
    language: "python",
    difficulty: "core",
    prompt: 'Write a function is_palindrome(text) that returns True when text reads the same forwards and backwards, ignoring case. is_palindrome("Level") should return True.',
    exampleCode: [
      "# Worked example: reversing a string with slicing.",
      "def reverse(text):",
      "    return text[::-1]",
      "",
      'print(reverse("abc"))  # cba',
    ].join("\n"),
    solutionCode: [
      "def is_palindrome(text):",
      "    lowered = text.lower()",
      "    return lowered == lowered[::-1]",
      "",
      'print(is_palindrome("Level"))  # True',
    ].join("\n"),
  },
  {
    kind: "practice_problem",
    id: "lists-largest",
    title: "Find the Largest Number",
    topics: ["lists", "arrays", "loops", "comparison"],
    language: "python",
    difficulty: "intro",
    prompt: "Write a function largest(numbers) that returns the largest value in a non-empty list without using the built-in max(). largest([3, 9, 4]) should return 9.",
    exampleCode: [
      "# Worked example: summing a list without the built-in sum().",
      "def total(numbers):",
      "    result = 0",
      "    for value in numbers:",
      "        result = result + value",
      "    return result",
      "",
      "print(total([3, 9, 4]))  # 16",
    ].join("\n"),
    solutionCode: [
      "def largest(numbers):",
      "    biggest = numbers[0]",
      "    for value in numbers:",
      "        if value > biggest:",
      "            biggest = value",
      "    return biggest",
      "",
      "print(largest([3, 9, 4]))  # 9",
    ].join("\n"),
  },
  {
    kind: "practice_problem",
    id: "dicts-word-count",
    title: "Count Word Frequencies",
    topics: ["dictionaries", "maps", "hash tables", "strings"],
    language: "python",
    difficulty: "core",
    prompt: 'Write a function word_count(text) that returns a dictionary mapping each word in text to how many times it appears. word_count("a b a") should return {"a": 2, "b": 1}.',
    exampleCode: [
      "# Worked example: counting each letter in a word with a dictionary.",
      "def letter_count(word):",
      "    counts = {}",
      "    for ch in word:",
      "        counts[ch] = counts.get(ch, 0) + 1",
      "    return counts",
      "",
      'print(letter_count("moon"))  # {"m": 1, "o": 2, "n": 1}',
    ].join("\n"),
    solutionCode: [
      "def word_count(text):",
      "    counts = {}",
      "    for word in text.split():",
      "        counts[word] = counts.get(word, 0) + 1",
      "    return counts",
      "",
      'print(word_count("a b a"))  # {"a": 2, "b": 1}',
    ].join("\n"),
  },
  {
    kind: "practice_problem",
    id: "recursion-factorial",
    title: "Recursive Factorial",
    topics: ["recursion", "base case", "call stack"],
    language: "python",
    difficulty: "core",
    prompt: "Write a recursive function factorial(n) that returns n! (the product of 1 through n), with factorial(0) returning 1. factorial(5) should return 120.",
    exampleCode: [
      "# Worked example: a recursive countdown with a base case.",
      "def countdown(n):",
      "    if n == 0:            # base case stops the recursion",
      '        print("Done")',
      "        return",
      "    print(n)",
      "    countdown(n - 1)      # recursive call moves toward the base case",
      "",
      "countdown(3)",
    ].join("\n"),
    solutionCode: [
      "def factorial(n):",
      "    if n == 0:",
      "        return 1",
      "    return n * factorial(n - 1)",
      "",
      "print(factorial(5))  # 120",
    ].join("\n"),
  },
  {
    kind: "practice_problem",
    id: "recursion-sum-digits",
    title: "Sum the Digits Recursively",
    topics: ["recursion", "integers", "modulo"],
    language: "python",
    difficulty: "core",
    prompt: "Write a recursive function sum_digits(n) that returns the sum of the digits of a non-negative integer. sum_digits(482) should return 14.",
    exampleCode: [
      "# Worked example: recursion peels one step off the problem each call.",
      "def count_down_by_tens(n):",
      "    if n <= 0:",
      "        return",
      "    print(n)",
      "    count_down_by_tens(n - 10)",
      "",
      "count_down_by_tens(30)  # 30, 20, 10",
    ].join("\n"),
    solutionCode: [
      "def sum_digits(n):",
      "    if n < 10:",
      "        return n",
      "    return n % 10 + sum_digits(n // 10)",
      "",
      "print(sum_digits(482))  # 14",
    ].join("\n"),
  },
  {
    kind: "practice_problem",
    id: "classes-bank-account",
    title: "Build a Bank Account Class",
    topics: ["classes", "objects", "oop", "methods", "attributes"],
    language: "python",
    difficulty: "core",
    prompt: "Write a class BankAccount with a starting balance of 0, a deposit(amount) method, and a withdraw(amount) method that only withdraws when the balance is sufficient and returns True or False accordingly.",
    exampleCode: [
      "# Worked example: a class with state and a method that changes it.",
      "class Counter:",
      "    def __init__(self):",
      "        self.count = 0",
      "",
      "    def increment(self):",
      "        self.count = self.count + 1",
      "",
      "c = Counter()",
      "c.increment()",
      "print(c.count)  # 1",
    ].join("\n"),
    solutionCode: [
      "class BankAccount:",
      "    def __init__(self):",
      "        self.balance = 0",
      "",
      "    def deposit(self, amount):",
      "        self.balance = self.balance + amount",
      "",
      "    def withdraw(self, amount):",
      "        if amount <= self.balance:",
      "            self.balance = self.balance - amount",
      "            return True",
      "        return False",
      "",
      "account = BankAccount()",
      "account.deposit(50)",
      "print(account.withdraw(60))  # False",
      "print(account.withdraw(20))  # True",
    ].join("\n"),
  },
  {
    kind: "practice_problem",
    id: "exceptions-safe-divide",
    title: "Divide Safely",
    topics: ["exceptions", "error handling", "try except"],
    language: "python",
    difficulty: "intro",
    prompt: "Write a function safe_divide(a, b) that returns a divided by b, or None when b is zero, using try/except rather than an if check.",
    exampleCode: [
      "# Worked example: catching a bad conversion instead of crashing.",
      "def to_int(text):",
      "    try:",
      "        return int(text)",
      "    except ValueError:",
      "        return 0",
      "",
      'print(to_int("42"))   # 42',
      'print(to_int("oops")) # 0',
    ].join("\n"),
    solutionCode: [
      "def safe_divide(a, b):",
      "    try:",
      "        return a / b",
      "    except ZeroDivisionError:",
      "        return None",
      "",
      "print(safe_divide(10, 2))  # 5.0",
      "print(safe_divide(10, 0))  # None",
    ].join("\n"),
  },
  {
    kind: "practice_problem",
    id: "sql-select-filter",
    title: "Filter and Sort with SELECT",
    topics: ["sql", "queries", "select", "where", "order by", "databases"],
    language: "sql",
    difficulty: "intro",
    prompt: "Given a table students(name, grade), write a query that returns the name and grade of every student with a grade of 90 or higher, sorted by name.",
    exampleCode: [
      "-- Worked example: selecting and filtering rows from a table.",
      "SELECT title, price",
      "FROM books",
      "WHERE price < 20",
      "ORDER BY price;",
    ].join("\n"),
    solutionCode: [
      "SELECT name, grade",
      "FROM students",
      "WHERE grade >= 90",
      "ORDER BY name;",
    ].join("\n"),
  },
  {
    kind: "practice_problem",
    id: "sql-join-count",
    title: "Count Enrollments per Course",
    topics: ["sql", "joins", "group by", "aggregation", "databases"],
    language: "sql",
    difficulty: "core",
    prompt: "Given courses(id, name) and enrollments(course_id, student_id), write a query that returns each course name with how many students are enrolled in it.",
    exampleCode: [
      "-- Worked example: joining two tables and grouping to count rows.",
      "SELECT authors.name, COUNT(*) AS book_count",
      "FROM authors",
      "JOIN books ON books.author_id = authors.id",
      "GROUP BY authors.name;",
    ].join("\n"),
    solutionCode: [
      "SELECT courses.name, COUNT(*) AS enrolled",
      "FROM courses",
      "JOIN enrollments ON enrollments.course_id = courses.id",
      "GROUP BY courses.name;",
    ].join("\n"),
  },
  {
    kind: "practice_problem",
    id: "js-filter-passing",
    title: "Filter Passing Students",
    topics: ["javascript", "arrays", "filter", "map", "functions"],
    language: "javascript",
    difficulty: "core",
    prompt: "Write a function passingStudents(students) that takes an array of {name, score} objects and returns an array of the names of students whose score is 70 or higher.",
    exampleCode: [
      "// Worked example: transforming an array of objects with map.",
      "function studentNames(students) {",
      "  return students.map(function (student) {",
      "    return student.name.toUpperCase();",
      "  });",
      "}",
      "",
      'console.log(studentNames([{ name: "Ada", score: 92 }]));  // ["ADA"]',
    ].join("\n"),
    solutionCode: [
      "function passingStudents(students) {",
      "  return students",
      "    .filter(function (student) {",
      "      return student.score >= 70;",
      "    })",
      "    .map(function (student) {",
      "      return student.name;",
      "    });",
      "}",
      "",
      'console.log(passingStudents([{ name: "Ada", score: 92 }, { name: "Bo", score: 55 }]));  // ["Ada"]',
    ].join("\n"),
  },
];
