// Shared accessibility-scan types. Client-safe (no server-only imports), so both
// the engine (server) and the UI/remediation (client) can import from here.

export type Severity = "error" | "warning" | "suggestion";

/**
 * How an issue is remediated. Drives the Fix button:
 * - "auto"     deterministic HTML transform, pre-applied in the editor
 * - "ai-alt"   alt text generated by AI (image description), pre-filled
 * - "ai-link"  link text generated by AI (describe destination), pre-filled
 * - "edit"     opens the editor focused on the node for a manual fix
 * - "flag"     informational only (no automatic fix, e.g. missing captions)
 */
export type FixKind = "auto" | "ai-alt" | "ai-link" | "edit" | "flag";

/** Locates the offending node inside an item's HTML so a fix can re-find it. */
export interface IssueLocator {
  /** CSS selector path (nth-of-type) relative to the content root. */
  selector: string;
  /** The node's outerHTML (truncated) — display + fallback matching. */
  snippet: string;
}

export interface Issue {
  /** Stable rule id, e.g. "image-alt", "heading-order", "link-text". */
  ruleId: string;
  severity: Severity;
  /** Human-readable description of what's wrong. */
  message: string;
  /** WCAG success criterion, e.g. "1.1.1". */
  wcag?: string;
  /** Short remediation hint. */
  help?: string;
  locator: IssueLocator;
  fixKind: FixKind;
  /** Pre-computed replacement value, when the engine can produce one. */
  suggestion?: string;
}

/** The editable Canvas content types we scan. */
export type AccessibleItemType =
  | "page"
  | "assignment"
  | "quiz"
  | "discussion"
  | "announcement"
  | "syllabus"
  | "file";

/** A single scanned item's result. */
export interface ItemScan {
  type: AccessibleItemType;
  /** Slug (pages) or content id (everything else); "syllabus" for the syllabus. */
  id: string;
  title: string;
  /** Canvas updated_at or a content hash — re-scan only when this changes. */
  fingerprint: string;
  errorCount: number;
  warningCount: number;
  suggestionCount: number;
  issues: Issue[];
}

/** Tally helper shared by the provider, pill, and badges. */
export function countsOf(issues: Issue[]): {
  errorCount: number;
  warningCount: number;
  suggestionCount: number;
} {
  let errorCount = 0;
  let warningCount = 0;
  let suggestionCount = 0;
  for (const i of issues) {
    if (i.severity === "error") errorCount += 1;
    else if (i.severity === "warning") warningCount += 1;
    else suggestionCount += 1;
  }
  return { errorCount, warningCount, suggestionCount };
}
