// Generates docs/BACKLOG.md from a list of BacklogItem. Deterministic: the
// same items array, regardless of input order, produces byte-identical
// output - check-generated.ts's whole safety rests on that (Ruling BA-6).

import type { BacklogItem, BacklogState } from "./types";

const SECTION_ORDER: BacklogState[] = ["actionable", "owner", "verification", "unscoped"];

const SECTION_META: Record<BacklogState, { heading: string; description: string }> = {
  actionable: {
    heading: "Actionable",
    description: "Worked by an agent. Leaves this section when `verify` exits 0 and actually runs at least one assertion (Ruling BA-2).",
  },
  owner: {
    heading: "Owner decision",
    description: "Never worked by an agent. Needs a human decision; the owner answers.",
  },
  verification: {
    heading: "Verification (owner)",
    description: "Never worked by an agent. Needs a live system or a real credential; the owner reports.",
  },
  unscoped: {
    heading: "Unscoped",
    description: "Lacks `owns`/`verify` (or both). Nobody works it until someone gives it both - fabricating either is worse than leaving it here (Ruling BA-2).",
  },
};

function escapeCell(value: string): string {
  return value.replace(/\|/g, "\\|").replace(/\r?\n/g, " ");
}

function cellList(values: string[]): string {
  return values.length === 0 ? "-" : escapeCell(values.join(", "));
}

function renderSection(state: BacklogState, items: BacklogItem[]): string {
  const meta = SECTION_META[state];
  const lines: string[] = [`## ${meta.heading}`, "", meta.description, ""];
  if (items.length === 0) {
    lines.push("_None._", "");
    return lines.join("\n");
  }
  lines.push("| id | title | owns | verify | blocked_by | instrument | from | note |");
  lines.push("|---|---|---|---|---|---|---|---|");
  const sorted = [...items].sort((a, b) => a.id.localeCompare(b.id));
  for (const item of sorted) {
    lines.push(
      `| ${escapeCell(item.id)} | ${escapeCell(item.title)} | ${cellList(item.owns)} | ` +
        `${item.verify === null ? "-" : escapeCell(item.verify)} | ${cellList(item.blocked_by)} | ` +
        `${item.instrument === "" ? "-" : escapeCell(item.instrument)} | ${item.from === "" ? "-" : escapeCell(item.from)} | ` +
        `${item.note === "" ? "-" : escapeCell(item.note)} |`
    );
  }
  lines.push("");
  return lines.join("\n");
}

export function renderBacklogMarkdown(items: BacklogItem[]): string {
  const header = [
    "# Backlog",
    "",
    "GENERATED by `npm run backlog:render` from `docs/backlog.yml` - do not",
    "hand-edit this file. `npm run backlog:check-generated` fails the moment it",
    "drifts from a fresh render (Ruling BA-6). Edit `docs/backlog.yml` instead,",
    "then re-render.",
    "",
    "Four sections, one per `state` (backlog-automation.md section 3): who works",
    "an item and how it leaves the queue depends only on which section it is in.",
    "Closing an item DELETES its row from `docs/backlog.yml` - there is no",
    "\"done\" state and no archive (Ruling BA-8); git history is the record.",
    "",
  ];
  const sections = SECTION_ORDER.map((state) =>
    renderSection(
      state,
      items.filter((i) => i.state === state)
    )
  );
  return `${[...header, ...sections].join("\n").replace(/\n+$/, "")}\n`;
}
